### ISSUE TITLE
Fluid Simulation Tasklist

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/sailbot_workspace#309]
### Purpose

Tracks the progress of the initial development of the fluid simulation classes. The high level implementation is outlined on [confluence](https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1809678337/Physics+Engine+Fluid+Simulation+Design+Specification#Fluid-Simulation), but this task list aims to break down the implementation.

### Tasks

- [x] UBCSailbot/boat_simulator#13 
- [x] UBCSailbot/boat_simulator#15 
- [x] UBCSailbot/sailbot_workspace#304
