### ISSUE TITLE
VS Code Configuration Improvements Tracker

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/sailbot_workspace#54]
### To Do
- [x] Install flake8 extension
- [x] Show whitespace at the end of lines (VS Code setting)
- [x] ~~Explore using [trunk](https://marketplace.visualstudio.com/items?itemName=Trunk.io) for all linting (VS Code and GitHub Actions)~~ using ROS native ament lint
- [ ] #39 
- [x] #55 
- [x] #64

**Comment by colinli02** [comment]
Both extension and whitespace setting done, under PR 110 

 https://github.com/UBCSailbot/docs/pull/110

**Comment by colinli02** [comment]
Devon has approved and merged to main

**Comment by colinli02** [comment]
I realise my PR 110 was for docs and I forgot to upload my local branch for sailbot_workspace with settings changes, hvae done that and PR made https://github.com/UBCSailbot/sailbot_workspace/pull/68

**Comment by patrick-5546** [comment]
only one issue left which can track itself, closing the tracker
